ServerName localhost

Listen 80

# Required MPM module
LoadModule mpm_event_module modules/mod_mpm_event.so

# Required proxy modules
LoadModule proxy_module modules/mod_proxy.so
LoadModule proxy_http_module modules/mod_proxy_http.so

<VirtualHost *:80>

    ProxyPreserveHost On

    ProxyPass        "/" "http://flask:5000/"
    ProxyPassReverse "/" "http://flask:5000/"

</VirtualHost>