version: "3.9"

services:

  flask:
    build: .
    container_name: flask-app

  apache:
    image: httpd:2.4
    container_name: apache-server

    ports:
      - "8080:80"

    volumes:
      - ./apache.conf:/usr/local/apache2/conf/httpd.conf

    depends_on:
      - flask